apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: messagebus
spec:
  type: pubsub.redis
  metadata:
  - name: redisHost
    value: YOUR_REDIS_HOST_HERE:6379
  - name: redisPassword
    value: YOUR_REDIS_KEY_HERE
